# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mod <- function(a, n) {
    .Call(`_PMDtest_mod`, a, n)
}

l_vec_compute_arma <- function(k, l_vec, cn_vec, m) {
    invisible(.Call(`_PMDtest_l_vec_compute_arma`, k, l_vec, cn_vec, m))
}

pmn_mdfft_arma <- function(nnt, pp, nn_vec, l_vec, cn_vec) {
    .Call(`_PMDtest_pmn_mdfft_arma`, nnt, pp, nn_vec, l_vec, cn_vec)
}

