---
title: "Accuracy_DFT-CF"
author: "zhengzhi"
date: "9/6/2021"
output: html_document
---

# Example 1
$$ \rm P_{4 \times 3} = \begin{pmatrix}
0.1 &  0.2 & 0.7\\
0.5 & 0.2 & 0.3\\
0.4 &  0.5 & 0.1\\
0.8 & 0.1 & 0.1
\end{pmatrix}
$$


```{r, echo=FALSE}
library(PMD)
library(poibin)
```

## Enumeration
The result of enumeration are shown below
```{r}
res <- matrix(c(0.0021, 0.0146, 0.0229, 0.0124, 0.002,
                0.0290, 0.1404, 0.1190, 0.0236, NA,
                0.1133, 0.2486, 0.0681, NA, NA,
                0.1276, 0.0604, NA, NA, NA,
                0.0160, NA, NA, NA, NA),5,byrow=T)
kable(res)
```

Result computed by \eqn{\rm 'DFT-CF'} is
```{r}
pp <- matrix(c(.1,.2,.7,.5,.2,.3,.4,.5,.1,.8,.1,.1),nrow=4,byrow=T)
kable(dpmd(pp))
```



# Test Accuracy With Binomial Distribution


Load in function that can generate \eqn{\rm pmat} randomly.

```{r}
p.matrix <- function(n,m){
  p <- matrix(0,nrow = n,ncol = m,byrow = T)
  for (i in 1:n) {
    r = runif(m)
    r = r/sum(r) #generate row
    r[1:(m-1)] = round(r[1:(m-1)],3)
    while(sum(r[1:(m-1)])>1){
      r = runif(m)
      r = r/sum(r) #generate row
      r[1:(m-1)] = round(r[1:(m-1)],3)
    }
    r[m] = 1-sum(r[1:(m-1)])
    p[i,] = r
  }
  return(p)
}

```

Accuracy result of using \eqn{\rm 'DFT-CF'}.
```{r}

m <- 2
n <- 1:100
N <- length(n)
K <- 1000
binom.res <- matrix(0, nrow = N, ncol = 3)
binom.res <- as.data.frame(binom.res)
colnames(binom.res) <- c('n','mae','tae')
temp <- binom.res[1,2:3]


for(i in 1:N){
  for(k in 1:K){
    p.bino <- p.matrix(n=1, m=2)
    pp <- matrix(rep(p.bino,10*i),nrow=10*i,byrow=T)
    mm <- ncol(pp) # m categories
    nn <- nrow(pp) # n people
    res0 <- dpmd(pp)
    res1 <- dbinom(0:nn, nn, p.bino[1])
    temp[1] <- max(abs(res0-res1))
    temp[2] <- sum(abs(res0-res1))
    binom.res[i,2:3] <- temp + binom.res[i,2:3]
  }
  binom.res$`n`[i] <- nn 
  binom.res[i,2:3] <- binom.res[i,2:3]/K
}

binom.res

plot(x=binom.res$`n`, y=binom.res$`mae`, type='l',
     main="Binomial vs 'DFT-CF'", xlab="n", ylab="mae")

plot(x=binom.res$`n`, y=binom.res$`tae`, type='l',
     main="Binomial vs 'DFT-CF'", xlab="n", ylab="tae")
```


# Test Accuracy With Poisson-Binomial Distribution

Accuracy result of using \eqn{\rm 'DFT-CF'}.

```{r}
m <- 2
n <- 1:100
N <- length(n)
K <- 1000
pbino.res <- matrix(0, nrow = N, ncol = 3)
pbino.res <- as.data.frame(pbino.res)
colnames(pbino.res) <- c('n','mae','tae')
temp <- pbino.res[1,2:3]


for(i in 1:N){
  for(k in 1:K){
  pp = p.matrix(10*i,m)
  mm=ncol(pp) # m categories
  nn=nrow(pp) # n people
  res0 = dpmd(pp)
  res1 = dpoibin(0:nn, pp[,1])
  temp[1] <- max(abs(res0-res1))
  temp[2] <- sum(abs(res0-res1))
  pbino.res[i,2:3] <- temp + pbino.res[i,2:3]
  }
  pbino.res$`n`[i] <- 10*i
  pbino.res[i,2:3] <- pbino.res[i,2:3]/K
}

pbino.res

plot(x=pbino.res$`n`, y=pbino.res$`mae`, type='l',
     main="Poisson-Binomial vs 'DFT-CF'", xlab="n", ylab="mae")

plot(x=pbino.res$`n`, y=pbino.res$`tae`, type='l',
     main="Poisson-Binomial vs 'DFT-CF'", xlab="n", ylab="tae")
```
