// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mod
int mod(int a, int n);
RcppExport SEXP _PMD_mod(SEXP aSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(mod(a, n));
    return rcpp_result_gen;
END_RCPP
}
// l_vec_compute_arma
void l_vec_compute_arma(int k, arma::vec& l_vec, arma::vec& cn_vec, int m);
RcppExport SEXP _PMD_l_vec_compute_arma(SEXP kSEXP, SEXP l_vecSEXP, SEXP cn_vecSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type l_vec(l_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type cn_vec(cn_vecSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    l_vec_compute_arma(k, l_vec, cn_vec, m);
    return R_NilValue;
END_RCPP
}
// pmn_mdfft_arma
arma::vec pmn_mdfft_arma(int nnt, arma::mat pp, arma::vec nn_vec, arma::vec l_vec, arma::vec cn_vec);
RcppExport SEXP _PMD_pmn_mdfft_arma(SEXP nntSEXP, SEXP ppSEXP, SEXP nn_vecSEXP, SEXP l_vecSEXP, SEXP cn_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nnt(nntSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type pp(ppSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type nn_vec(nn_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type l_vec(l_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type cn_vec(cn_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(pmn_mdfft_arma(nnt, pp, nn_vec, l_vec, cn_vec));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PMD_mod", (DL_FUNC) &_PMD_mod, 2},
    {"_PMD_l_vec_compute_arma", (DL_FUNC) &_PMD_l_vec_compute_arma, 4},
    {"_PMD_pmn_mdfft_arma", (DL_FUNC) &_PMD_pmn_mdfft_arma, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_PMD(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
