# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Mod
#' @param a integer
#' @param n integer
#' @return a - floor(a/n)*n
mod <- function(a, n) {
    .Call(`_PMD_mod`, a, n)
}

#' l.vec.cmpt
#' @param k interger
#' @param l_vec vector
#' @param cn_vec vector
#' @param m integer
l_vec_compute_arma <- function(k, l_vec, cn_vec, m) {
    invisible(.Call(`_PMD_l_vec_compute_arma`, k, l_vec, cn_vec, m))
}

#' mdfft method
#' @param nnt interger
#' @param pp matrix
#' @param nn_vec vector
#' @param l_vec vector
#' @param cn_vec vector
#' @return result
pmn_mdfft_arma <- function(nnt, pp, nn_vec, l_vec, cn_vec) {
    .Call(`_PMD_pmn_mdfft_arma`, nnt, pp, nn_vec, l_vec, cn_vec)
}

